{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "074cf7f7-9903-4e04-a7a4-9532378263f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "while True:\n",
    "\n",
    "    board = [\" \", \" \", \" \",\n",
    "             \" \", \" \", \" \",\n",
    "             \" \", \" \", \" \"]\n",
    "\n",
    "    current_player = \"X\"\n",
    "\n",
    "\n",
    "    def show_board():\n",
    "\n",
    "        print()\n",
    "        print(board[0], \"|\", board[1], \"|\", board[2])\n",
    "        print(\"---------\")\n",
    "\n",
    "        print(board[3], \"|\", board[4], \"|\", board[5])\n",
    "        print(\"---------\")\n",
    "\n",
    "        print(board[6], \"|\", board[7], \"|\", board[8])\n",
    "        print()\n",
    "\n",
    "\n",
    "    def check_winner():\n",
    "\n",
    "        # Rows\n",
    "        if board[0] == board[1] == board[2] != \" \":\n",
    "            return True\n",
    "\n",
    "        if board[3] == board[4] == board[5] != \" \":\n",
    "            return True\n",
    "\n",
    "        if board[6] == board[7] == board[8] != \" \":\n",
    "            return True\n",
    "\n",
    "        # Columns\n",
    "        if board[0] == board[3] == board[6] != \" \":\n",
    "            return True\n",
    "\n",
    "        if board[1] == board[4] == board[7] != \" \":\n",
    "            return True\n",
    "\n",
    "        if board[2] == board[5] == board[8] != \" \":\n",
    "            return True\n",
    "\n",
    "        # Diagonals\n",
    "        if board[0] == board[4] == board[8] != \" \":\n",
    "            return True\n",
    "\n",
    "        if board[2] == board[4] == board[6] != \" \":\n",
    "            return True\n",
    "\n",
    "        return False\n",
    "\n",
    "\n",
    "    def check_tie():\n",
    "\n",
    "        if \" \" not in board:\n",
    "            return True\n",
    "\n",
    "        return False\n",
    "\n",
    "\n",
    "    while True:\n",
    "\n",
    "        show_board()\n",
    "\n",
    "        position = int(input(f\"Player {current_player}, enter position (0-8): \"))\n",
    "\n",
    "        if board[position] == \" \":\n",
    "\n",
    "            board[position] = current_player\n",
    "\n",
    "        else:\n",
    "            print(\"Position already taken!\")\n",
    "            continue\n",
    "\n",
    "\n",
    "        if check_winner():\n",
    "\n",
    "            show_board()\n",
    "            print(f\"Player {current_player} wins!\")\n",
    "            break\n",
    "\n",
    "\n",
    "        if check_tie():\n",
    "\n",
    "            show_board()\n",
    "            print(\"It's a tie!\")\n",
    "            break\n",
    "\n",
    "\n",
    "        if current_player == \"X\":\n",
    "            current_player = \"O\"\n",
    "\n",
    "        else:\n",
    "            current_player = \"X\"\n",
    "\n",
    "\n",
    "    play_again = input(\"Do you want to play again? (yes/no): \")\n",
    "\n",
    "    if play_again != \"yes\":\n",
    "        print(\"Thanks for playing!\")\n",
    "        break"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
